GET https://api.themoviedb.org/3/movie/550?api_key=67827dade2847df4df3fa8f7f2a00f55

###
GET https://api.themoviedb.org/3/discover/movie/?api_key=67827dade2847df4df3fa8f7f2a00f55

###
GET https://api.themoviedb.org/3/trending/all/week?api_key=67827dade2847df4df3fa8f7f2a00f55


###
GET https://api.themoviedb.org/3/movie/453395?api_key=67827dade2847df4df3fa8f7f2a00f55&language=en-US

###
GET https://api.themoviedb.org/3/movie/453395?api_key=67827dade2847df4df3fa8f7f2a00f55&append_to_response=credits

###
GET https://api.themoviedb.org/3/movie/453395?api_key=67827dade2847df4df3fa8f7f2a00f55&append_to_response=credits

###
GET https://api.themoviedb.org/3/movie/453395/recommendations?api_key=67827dade2847df4df3fa8f7f2a00f55&language=en-US&page=1